version: '3'

services:
  filebeat:
    build: ./filebeat
    volumes:
      - ./filebeat/var/log/httpd:/var/log/httpd
      - ./filebeat/var/log/nginx:/var/log/nginx
    networks:
      - log-collection

networks:
  log-collection:
    external: true